#!/bin/bash
set -e
set -u

./install-dependencies.sh

# so all files inside the rpm have mode 0644
umask 022

####UNIFY####
UNIFIED=./src/unified.js
SOURCE=./src/eyeos-http-relay-server.js
OUTPUT=./src/eyeos-http-relay-server.js
FILENAME=eyeos-http-relay-server.js
EXCLUDEDIR=./src/test,./src/component-test
CLEANDIR=src/lib
PRESERVE_LIB_SETTINGS=true

sudo npm install node-unify uglify-js -g --registry=http://artifacts.eyeosbcn.com/nexus/content/groups/npm/ || true

node-unify --dp `pwd` --ep $SOURCE --inDir ./src --exDir $EXCLUDEDIR -v > $UNIFIED
echo -e "#!/usr/bin/env node" > $OUTPUT
uglifyjs -c -m --keep-fnames -- $UNIFIED >> $OUTPUT
chmod +x $OUTPUT


if [ ! -d "./tmp" ]; then
  mkdir ./tmp
fi
if [ "$PRESERVE_LIB_SETTINGS" = true ]; then
  cp ./src/lib/settings.js ./tmp
fi
cp $OUTPUT ./tmp
rm -rf ./$CLEANDIR
mkdir ./$CLEANDIR

if [ "$PRESERVE_LIB_SETTINGS" = true ]; then
  cp ./tmp/settings.js ./src/lib/
fi
cp ./tmp/$FILENAME ./src/
rm $UNIFIED
rm -rf ./tmp
####END OF UNIFY####

cd builder

./build.sh
